apiVersion: v1
kind: Pod
metadata: 
  name: webapp
  labels: 
    vishnu: app

spec:
  containers:
    - name: webapp
      image: nagavagiletech/fleetman-angular:release0
---

apiVersion: v1
kind: Pod
metadata: 
  name: webappv1
  labels: 
    version: new

spec:
  containers:
    - name: webapp
      image: nagavagiletech/fleetman-angular:release5
